const ChatActionTypes = {
  SET_CHANNELS: 'SET_CHANNELS',
  SET_CURRENT_CHANNEL: 'SET_CURRENT_CHANNEL',
  UPDATE_CHANNEL_MEMBERS: 'UPDATE_CHANNEL_MEMBERS',
  SET_MESSAGE_SEARCH_FILTERS: 'SET_MESSAGE_SEARCH_FILTERS',
  SET_PRIVATE_CHANNEL: 'SET_PRIVATE_CHANNEL',
  SET_OTHER_USERS_STATUS: 'SET_OTHER_USERS_STATUS',
  SET_STARRED_CHANNELS: 'SET_STARRED_CHANNELS'
}

export default ChatActionTypes
