const ChatActionTypes = {
  SET_CURRENT_CHANNEL: 'SET_CURRENT_CHANNEL',
  UPDATE_CHANNEL_MEMBERS: 'UPDATE_CHANNEL_MEMBERS',
  SET_MESSAGE_SEARCH_FILTERS: 'SET_MESSAGE_SEARCH_FILTERS'
}

export default ChatActionTypes
