const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  CLEAR_CURRENT_USER: 'CLEAR_CURRENT_USER',
  SET_USER_IS_LOADING: 'SET_USER_IS_LOADING',
  SET_USER_STATUS: 'SET_USER_STATUS',
  SET_STARRED_CHANNELS: 'SET_STARRED_CHANNELS'
}

export default UserActionTypes
